backend:
  name: git-gateway
  branch: main # o 'master', según cómo se llame la rama principal en tu GitHub

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre del Producto", name: "title", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Foto", name: "image", widget: "image"}
