backend:
  name: github
  repo: Davidk280898/dpansaludybienestar
  branch: main
  auth_type: implicit
  app_id: 2267462

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "public/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Precio", name: "price", widget: "number" }
